### ISSUE TITLE
Handle PLATFORMIO_* Environment variables

### ISSUE THREAD

**Issue by ivankravets** [ivankravets/platformio#102]
- [x] Add new section "Environment variables" to documentation
- [x] Add variable `PLATFORMIO_HOME_DIR` - see http://docs.platformio.org/en/latest/projectconf.html#home-dir
- [x] Add variable `PLATFORMIO_LIB_DIR` - see http://docs.platformio.org/en/latest/projectconf.html#lib-dir
- [x] Add variable `PLATFORMIO_SRC_DIR` - see http://docs.platformio.org/en/latest/projectconf.html#src-dir
- [x] Add variable `PLATFORMIO_ENVS_DIR` - see https://github.com/ivankravets/platformio/blob/develop/platformio/util.py#L112
- [x] Add variable `PLATFORMIO_SRCBUILD_FLAGS` - see https://github.com/ivankravets/platformio/blob/develop/platformio/builder/tools/platformio.py#L67
- [x] Handle variables `PLATFORMIO_SETTING_${SETTING_NAME}` from http://docs.platformio.org/en/latest/userguide/cmd_settings.html

**Comment by pelikhan** [comment]
+1 for these.

**Comment by ivankravets** [comment]
Implemented in https://github.com/ivankravets/platformio/commit/ae92cdedeaadeae51b34bd3e22ac177102aa5dcb

**Comment by ivankravets** [comment]
Documentation: http://docs.platformio.org/en/latest/envvars.html
