### ISSUE TITLE
Automatically append -DPLATFORMIO to builder

### ISSUE THREAD

**Issue by ivankravets** [ivankravets/platformio#105]
Add `PLATFORMIO` define to `gcc` builder which should be equal to `platformio.__version__` in the INT format (4bytes):
1byte = major version
2byte = minor version
3byte = bug fixes number
4byte = dev/pre/post/alpha/beta and etc

Pack this information in `MSB` order.

**Comment by aphelps** [comment]
Hah, thanks for adding that.  I had already put the same tag into all my own platformio.ini files ;)

**Comment by ivankravets** [comment]
Why you haven't requested it earlier? :smile: Do you have any ideas/propositions as for 1.1.0 release?

**Comment by aphelps** [comment]
Didn't think about it, its been a couple of weeks since I've had time to work on the software as I've needed to update the boards I've been running on it.  I'll contemplate new ideas, I should be back to software development this week.

**Comment by ivankravets** [comment]
> I'll contemplate new ideas, I should be back to software development this week.

Thanks! We will wait for them (ideas) :+1:
