### ISSUE TITLE
Add support for panStamp AVR

### ISSUE THREAD

**Issue by gandy92** [ivankravets/platformio#117]
Is it possible to add support for the panStamp AVR and panStamp NRG boards?
* Vendor: http://www.panstamp.com/
* panStamp AVR: https://github.com/panStamp/panstamp/wiki/panStamp%20AVR.-Technical%20details
* panStamp NRG: https://github.com/panStamp/panstamp/wiki/panStamp%20NRG.-Technical%20details
* Libraries for panStamp specific hardware: https://github.com/panStamp/panstamp

**Comment by gandy92** [comment]
Thank you for adding support for panstamp so promptly :+1:

I managed to successfully build the panstamp-blink.ino. However, I have a few issues compiling a sketch that uses the Wire lib, similar to what is mentioned here:  http://www.panstamp.org/forum/archive/index.php/thread-3978.html  Apparently, using the panstamp libraries requires a few patches to the libraries shipped with arduino.

Should I open a new issue covering this?

**Comment by gandy92** [comment]
I looked into this more closely, apparently they just rename twi.c from libraries/Wire/utility to twi.cpp to make it work. Would this be a viable solution?

**Comment by ivankravets** [comment]
@gandy92 thanks for report. I've just opened new issue #133 . It should resolve this problem.

P.S: You can currently avoid this problem via adding specific libs to your project ``libs`` directory. These libs have more higher priority then framework's libs. Just copy PanStamp's ``Wire`` lib to projects ``libs/Wire``. Did it help you?

**Comment by gandy92** [comment]
Thanks for the workaround. For a preliminary fix I manually copied the libraries to the platformio directories. Your solution is much more elegant, though, I will try this with a clean installation, tomorrow.

**Comment by ivankravets** [comment]
Ok, I will wait for your results.

P.S: Please restore default PlatformIO packages. Just uninstall/install specified platforms or remove totally ``~/.platformio`` dir.

**Comment by gandy92** [comment]
Removed .platformio dir and copied panstamp-avr specific libraries to lib/

Worked fine for both of my projects. :+1:
