### ISSUE TITLE
Add support for Sanguino boards (atmega1284p)

### ISSUE THREAD

**Issue by robseee** [ivankravets/platformio#131]
Please add support for Sanguino boards (used in 3d printers)
Pins definitions seems wrong with platformio.

Arduino board definition is here:
https://github.com/MarlinFirmware/Marlin/tree/Development/ArduinoAddons/Arduino_1.5.x/hardware/marlin/avr

I successfully compiled and uploaded to this board with platformio using command "platformio init --board=1284p16m" and adding upload_speed = 57600 to platformio.ini, but looks like that pins definitions are wrong.

I can't get proper values (like those returned when compiling and uploading with arduino) for this program:
void setup() {
  Serial.begin(9600);
  pinMode(17, INPUT);
}

void loop()
{
 myread = analogRead(17);
 Serial.println(myread);
}

It should return pin 17 analog read (buttons attached to it), instead I get a fixed value coming from nowhere.

Thank you

**Comment by ivankravets** [comment]
>  but looks like that pins definitions are wrong.

This is obvious behaviour, because the "PINs MAP" of ``1284p16m`` isn't equal to Sanguino board. We will add support for this board.
