### ISSUE TITLE
Support Arduino IDE compatible file layout

### ISSUE THREAD

**Issue by pelikhan** [ivankravets/platformio#41]
When trying to open a sketch file in Arduous IDE from the src folder, it insist on moving it to a sketch folder.
Could pio support a file layout that just works with arduous ide? (Or at least as much as possible).

**Comment by pelikhan** [comment]
Do you mean to rename the file or the folder?

**Comment by ivankravets** [comment]
> Do you mean to rename the file or the folder?
File. Like:
```
.
lib
src
   |-- src.ino
platformio.ini
```

**Comment by ivankravets** [comment]
@pelikhan @aphelps did you try this solution?

**Comment by aphelps** [comment]
I did verify that it would compile those src.ino files over the holidays, but its going to be a bit before I get time again to play with this extensively.  I have some projects that need to be converted to a better make system than the IDE (and platformio looks to be one of the best options), but they're pretty extensive with a bunch of library dependencies (both personal libraries and 3rd party ones) so its going to take me a good bit of work to make the switch.  I'll definitely let you know if I hit issues that seem to be related to platformio once I get to the time to work on the conversion (probably a week or two).

**Comment by ivankravets** [comment]
>  but they're pretty extensive with a bunch of library dependencies (both personal libraries and 3rd party ones)
You can use 3rd party libraries from [Library Registry](http://platformio.org/#!/lib). If some libs are not listed here, please tell me and I will add them.

As for "own" libs - just move them to `lib` dir in project. PlatformIO will automatically use them.

**Comment by pelikhan** [comment]
Solution works great.
