### ISSUE TITLE
Support for json output in cli commands

### ISSUE THREAD

**Issue by pelikhan** [ivankravets/platformio#42]
An option to dump data as JSON in the console output would be handhandy for commands like list and such. It avoids having to write parsers around the output of clients when automatingoing it.

**Comment by pelikhan** [comment]
Imo, (1) would be bwst. Just --json.

On Sunday, December 28, 2014, Ivan Kravets <notifications@github.com> wrote:

> What do you think, which way is better to tell PlatformIO for json output?
> 1. Additional option to specific command, like $ platformio list
> --output=json
> 2. Global settings$ platformio settings set output_json yes`
>
> I'm not sure that I can implement normal json output for each command,
> but I can try.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ivankravets/platformio/issues/42#issuecomment-68211919>
> .
>


-- 
This posting is provided "AS IS" with no warranties, and confers no rights.

**Comment by ivankravets** [comment]
> Imo, (1) would be bwst. Just --json.

Give me please a list with the commands which should return JSON response.

Thanks.

**Comment by pelikhan** [comment]
All the list commands, platforms, serial ports, libraries, etc...

On Friday, January 2, 2015, Ivan Kravets <notifications@github.com> wrote:

> Imo, (1) would be bwst. Just --json.
>
> Give me please a list with the commands which should return JSON response.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ivankravets/platformio/issues/42#issuecomment-68543889>
> .
>


-- 
This posting is provided "AS IS" with no warranties, and confers no rights.

**Comment by pelikhan** [comment]
The JSON produced is invalid. You can use online tools like JsonLint to validate it.

**Comment by pelikhan** [comment]
What also adding for the boards option?
