### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by ilaizz** [ivankravets/platformio#46]
Mac OS 10.9.5

Get the following message:

Command '['/usr/bin/python', '-m', 'pip', 'install', '-U', 'platformio']' returned non-zero exit status 2
[FAILURE]
The installation process has been FAILED!

**Comment by ivankravets** [comment]
Did you try with `sudo` permission?
```shell
sudo python -c "$(curl -fsSL https://raw.githubusercontent.com/ivankravets/platformio/master/scripts/get-platformio.py)"
```

**Comment by ilaizz** [comment]
Thanks, that solved the problem
