### ISSUE TITLE
Migrate to Arduino Framework 1.6.0

### ISSUE THREAD

**Issue by ivankravets** [ivankravets/platformio#68]
- [x] update dependent libraries 
- [x] verify `build_flags`
- [x] re-pack `framework-arduinoavr` package
- [x] re-pack `framework-arduinosam` package
- [x] correct documentation that we use Arduino 1.6.x branch
- [x] correct Web-site that we use Arduino 1.6.x branch

**Comment by aphelps** [comment]
It might be a good idea to retain the previous framework as an option for a bit.  I know when they initially moved from the 1.0 branch to the 1.5 one that there were some incompatibilities with existing libraries, I haven't been paying much attention to the 1.6 release process so don't know how likely this release is to break existing code.

**Comment by ivankravets** [comment]
@aphelps 1.5.x has not been released in "stable" version. It was like "beta". The 1.6 is "stable" version after 1.5.x. In other words, 1.6 is fully compatible with 1.5.x. See [Arduino Release Notes](http://www.arduino.cc/en/Main/ReleaseNotes)

**Comment by aphelps** [comment]
Cool, should be fine then.  I'll definitely try it out when you make the switch

**Comment by ivankravets** [comment]
@aphelps Which types of boards do you have? :blush:

**Comment by ivankravets** [comment]
@aphelps Please update your PlatformIO packages:
```shell
> platformio update
```
