### ISSUE TITLE
Improvements to "platformio run" command

### ISSUE THREAD

**Issue by ivankravets** [ivankravets/platformio#74]
- [x] Cleanup automatically `.pioenvs` when `platformio.ini` has been changed
- [x] Add "start", "end" and "took" time info per environment
- [x] Add detailed info about environment based on `platformio.ini`: platform, framework, board...
- [x] Implement asynchronous output for build process

**Comment by ivankravets** [comment]
Dear @aphelps, @franciscoruiz, @pelikhan, @valeros, @laurentS, @yarekt, @bettabacon, @eiginn,  @mac7, @MrCustomizer, @elyulka

* Current [HISTORY of 1.0.0](http://docs.platformio.org/en/latest/history.html).
* [Active issues for 1.0.0 milestone](https://github.com/ivankravets/platformio/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0)

Could you help me with testing this issue? The `platformio run` command was seriously refactored. I want to know that it works good with your projects. If we wont have new issues, then I will release `1.0.0` this week.

1. [Install the latest development version of PlatformIO](http://docs.platformio.org/en/latest/installation.html#development-version)
2. Update packages: `$ platformio update`
3. Test your projects :blush: 

Thanks a lot!

**Comment by franciscoruiz** [comment]
Sure thing!

I'll give a go next week or so and I'll let you know how it goes.

Cheers

Francisco Ruiz

**Comment by aphelps** [comment]
I should be able to give this a try later this week

**Comment by eiginn** [comment]
Same, will give it a try later in the week

**Comment by MrCustomizer** [comment]
Success! The current version of the development branch is still working with my current project.

**Comment by MrCustomizer** [comment]
I nearly forgot to test it on Windows. My first test was on a Linux machine. Windows works, too.

**Comment by ivankravets** [comment]
@MrCustomizer Which type of board do you have? Did you test upload operation?

**Comment by MrCustomizer** [comment]
I have an Arduino Nano, but I haven't tested uploading as I'm issuing a custom command for uploading via bluetooth and I haven't had the time yet to figure out how to do that with platformio. Perhaps someone else could test uploading?

**Comment by ivankravets** [comment]
@MrCustomizer Yes, thanks for it! I hope it works without any problems :beer: :smile:

**Comment by aphelps** [comment]
I've updated and done clean compiles of my projects, including uploading to an Arduino Nano and a Mini Pro.  All looks fine so far.

**Comment by ivankravets** [comment]
Thanks! I'm going to close this issue. If you have any problems with it, don't hesitate to reopen

**Comment by franciscoruiz** [comment]
I've used it pretty thoroughly now, both with TI Launchpad and Arduino UNO; and it works like charm! :+1:

**Comment by ivankravets** [comment]
@franciscoruiz Thank you for the feedback :+1: :blush:
