### ISSUE TITLE
Library config using YAML

### ISSUE THREAD

**Issue by ricardojlrufino** [ivankravets/platformio#91]
its a more easy format
http://docs.platformio.org/en/latest/librarymanager/config.html

**Comment by ivankravets** [comment]
@ricardojlrufino I'm agree with you that `YAML` is more readable. However, this format doesn't have native parsers within the most popular languages. I mean, that developer should install additional libraries/packages to work with this format. To my mind, `JSON` is more standardised cross-format for configuration aims.

**Comment by ricardojlrufino** [comment]
It's a bit boring to write in JSON, is usually thing the computer does.
May be an additional format

**Comment by ivankravets** [comment]
You can write in `YAML` and [convert it to JSON](http://yamltojson.com).

**Comment by ricardojlrufino** [comment]
His tool could do that ... just a tip

**Comment by ivankravets** [comment]
@ricardojlrufino thanks a lot for tip. If you have any problems with converting `YAML` to `JSON` - please re-open this issue.
